'GESTIÓN DE EMPLEADOS

' DEBE PERMITIR CREAR UN MÍNIMO DE 4 EMPLEADOS CON LOS SIGUIENTES DATOS
' NOMBRE, HORAS TRABAJADAS Y TARIFA POR HORA
' SE DEBEN IMPLEMENTAR PROCEDIMIENTOS O FUNCIONES PARA CALCULAR EL SALARIO DE UN EMPLEADO
' MOSTRAR LA INFORMACIÓN DE LOS EMPLEADOS
' MOSTRAR O CALCULAR EL SALARIO TOTAL DE TODOS LOS EMPLEADOS DE LA EMPRESA
' DEBE PERMITIR AUMENTAR EL SALARIO DE UN EMPLEADO EN UN PORCENTAJE DADO
' DEBE PERMITIR ELIMINAR A UN EMPLEADO DEL SISTEMA
' CALCULAR EL SALARIO PROMEDIO DE LOS EMPLEADOS REGISTRADOS
' DEBERÁ ENTREGAR EL NOMBRE DEL EMPLEADO CON EL SALARIO MÁS ALTO
' DEBERÁ ENTREGAR EL O LOS NOMBRES DE LOS EMPLEADOS QUE CUYOS SALARIOS
' SEAN IGUALES O SUPERIORES A UN UMBRAL ESPECIFICADO POR EL USUARIO